environment:
  matrix:
    - TARGET_ARCH: x64
      CONDA_PY: 27
      CONDA_INSTALL_LOCN: C:\\Miniconda-x64
      GDAL_DATA: C:\Miniconda-x64\Library\share\gdal


# We always use a 64-bit machine, but can build x86 distributions
# with the TARGET_ARCH variable.
platform:
    - x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    - cmd: |
        powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py', 'ff_ci_pr_build.py')"
        ff_ci_pr_build -v --ci "appveyor" "%APPVEYOR_ACCOUNT_NAME%/%APPVEYOR_PROJECT_SLUG%" "%APPVEYOR_BUILD_NUMBER%" "%APPVEYOR_PULL_REQUEST_NUMBER%"
        del ff_ci_pr_build.py

    # Cywing's git breaks conda-build. (See https://github.com/conda-forge/conda-smithy-feedstock/pull/2.)
    - cmd: rmdir C:\cygwin /s /q

    # Add path, activate `conda` and update conda.
    - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
    - cmd: conda.exe update --yes --quiet conda

    - cmd: set PYTHONUNBUFFERED=1

    # Add our channels.
    - cmd: conda.exe config --set show_channel_urls true
    - cmd: conda.exe config --remove channels defaults
    - cmd: conda.exe config --add channels defaults
    - cmd: conda.exe config --add channels conda-forge

    # Configure the VM.
    - cmd: conda.exe install -n root --quiet --yes gdal numpy pillow netcdf4 python-dateutil nose coveralls mock urllib3 basemap
    - cmd: python.exe setup.py install

# Skip .NET project specific build phase.
build: off

test_script:
    - coverage run --omit=nansat/mappers/*,nansat/tests/*,nansat/nansatmap.py --source=nansat setup.py test
