#!/usr/bin/env python
#
# Analogue to gdalinfo, but for Nansat datasets 
# Refers to Nansat band numbers

import sys

if (len(sys.argv) != 2):
    sys.exit('Usage: nansatinfo <filename>')

from nansat import Nansat
n = Nansat(sys.argv[1])
print n