#!/usr/bin/env python
#
# Analogue to gdalinfo, but for Nansat datasets 
# Refers to Nansat band numbers

import sys
from os.path import dirname, abspath

try:
    from nansat import Nansat
except ImportError: # development
    sys.path.append(dirname(dirname(abspath(__file__))))
    from nansat import Nansat

if (len(sys.argv) != 2):
    sys.exit('Usage: nansatinfo <filename>')

n = Nansat(sys.argv[1])
print n
