---
channels:
  - conda-forge
dependencies:
  - python=3.6
  - libnetcdf=4.4.1.1
  - gdal
  - numpy
  - pillow
  - netcdf4
  - python-dateutil
  - nose
  - coveralls
  - mock
  - urllib3
  - pythesint
